# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-devel

sudo: false
cache: packages

notifications:
  email:
    - koohoko@gmail.com

bioc_check: true